-- AlterTable
ALTER TABLE "User" ADD COLUMN     "EarnedPoints" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "SolvedEasy" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "SolvedHard" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "SolvedMedium" INTEGER[] DEFAULT ARRAY[]::INTEGER[];
