// --- template _header.gotpl ---
// Code generated by Prisma Client Go. DO NOT EDIT.
//nolint
//go:build !codeanalysis
// +build !codeanalysis

package db

import (
	"context"
	"fmt"
	"os"
	"slices"
	"testing"

	// no-op import for go modules
	_ "github.com/joho/godotenv"
	_ "github.com/shopspring/decimal"

	"github.com/steebchen/prisma-client-go/engine"
	"github.com/steebchen/prisma-client-go/engine/mock"
	"github.com/steebchen/prisma-client-go/runtime/builder"
	"github.com/steebchen/prisma-client-go/runtime/lifecycle"
	"github.com/steebchen/prisma-client-go/runtime/raw"
	"github.com/steebchen/prisma-client-go/runtime/transaction"
	"github.com/steebchen/prisma-client-go/runtime/types"
	rawmodels "github.com/steebchen/prisma-client-go/runtime/types/raw"
)

// ignore unused os import as it may not be needed depending on engine type
var _ = os.DevNull

// re-declare variables which are needed in Prisma Client Go but also should be exported
// in the generated client

type PrismaTransaction = transaction.Transaction

const RFC3339Milli = types.RFC3339Milli

type BatchResult = types.BatchResult

type Boolean = bool
type String = string
type Int = int
type Float = float64

type DateTime = types.DateTime
type JSON = types.JSON
type Bytes = types.Bytes
type BigInt = types.BigInt
type Decimal = types.Decimal

type RawString = rawmodels.String
type RawInt = rawmodels.Int
type RawFloat = rawmodels.Float
type RawBoolean = rawmodels.Boolean
type RawDateTime = rawmodels.DateTime
type RawJSON = rawmodels.JSON
type RawBytes = rawmodels.Bytes
type RawBigInt = rawmodels.BigInt
type RawDecimal = rawmodels.Decimal

// deprecated: use SortOrder
type Direction = SortOrder

const (
	// deprecated: use SortOrderAsc
	ASC Direction = "asc"
	// deprecated: use SortOrderDesc
	DESC Direction = "desc"
)

// --- template client.gotpl ---
const datasources = `[{"name":"db","provider":"postgresql","activeProvider":"postgresql","url":{"fromEnvVar":"","value":"postgresql://games_user:games_pass@localhost:5434/games?schema=public"},"config":null}]`

const schema = `// prisma_games/schema.prisma

datasource db {
  provider = "postgresql"
  url      = "postgresql://games_user:games_pass@localhost:5434/games?schema=public"
}

generator client {
  provider = "prisma-client-go"
  output   = "./prisma_games_client" // separate client folder
}

model Game {
  id          Int      @id @default(autoincrement())
  title       String
  genre       String
  releaseDate DateTime
  developer   String
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}
`
const schemaDatasourceURL = "postgresql://games_user:games_pass@localhost:5434/games?schema=public"
const schemaEnvVarName = ""

// hasBinaryTargets is true when binaryTargets are provided on generation time
var hasBinaryTargets = true

// NewClient creates a new Prisma Client Go client.
// The client is not connected to the Prisma engine yet.
//
// Example:
//
//	client := db.NewClient()
//	if err := client.Prisma.Connect(); err != nil {
//	  handle(err)
//	}
//
//	defer func() {
//	  if err := client.Prisma.Disconnect(); err != nil {
//	    panic(fmt.Errorf("could not disconnect: %w", err))
//	  }
//	}()
func NewClient(options ...func(config *PrismaConfig)) *PrismaClient {
	var config PrismaConfig
	for _, option := range options {
		option(&config)
	}

	c := newClient()

	// use the schema connection url if set
	url := config.datasourceURL
	if url == "" {
		url = schemaDatasourceURL
		if url == "" {
			// if not, use the schema env var name
			url = os.Getenv(schemaEnvVarName)
			if url == "" {
				//panic("no connection string found")
				println("WARNING: env var which was defined in the Prisma schema is not set " + schemaEnvVarName)
			}
		}
	}

	c.Engine = engine.NewQueryEngine(schema, hasBinaryTargets, datasources, url)

	c.Prisma.Lifecycle = &lifecycle.Lifecycle{Engine: c.Engine}

	return c
}

type PrismaConfig struct {
	datasourceURL string
}

func WithDatasourceURL(url string) func(*PrismaConfig) {
	return func(config *PrismaConfig) {
		config.datasourceURL = url
	}
}

func newMockClient(expectations *[]mock.Expectation) *PrismaClient {
	c := newClient()
	c.Engine = mock.New(expectations)
	c.Prisma.Lifecycle = &lifecycle.Lifecycle{Engine: c.Engine}

	return c
}

func newClient() *PrismaClient {
	c := &PrismaClient{}
	c.Game = gameActions{client: c}

	c.Prisma = &PrismaActions{
		Raw: &raw.Raw{Engine: c},
		TX:  &transaction.TX{Engine: c},
	}
	return c
}

type PrismaActions struct {
	*lifecycle.Lifecycle
	*raw.Raw
	*transaction.TX
}

// PrismaClient is the instance of the Prisma Client Go client.
type PrismaClient struct {
	// engine is an abstractions of what happens under the hood
	// the query engine can spawn and manage the binary and send requests to it,
	// while a mock engine would collect mocks to verify them later
	engine.Engine

	// prisma provides prisma-related methods as opposed to model methods, such as Connect, Disconnect or raw queries
	Prisma *PrismaActions

	// Game provides access to CRUD methods.
	Game gameActions
}

// --- template enums.gotpl ---

type TransactionIsolationLevel string

const (
	TransactionIsolationLevelReadUncommitted TransactionIsolationLevel = "ReadUncommitted"
	TransactionIsolationLevelReadCommitted   TransactionIsolationLevel = "ReadCommitted"
	TransactionIsolationLevelRepeatableRead  TransactionIsolationLevel = "RepeatableRead"
	TransactionIsolationLevelSerializable    TransactionIsolationLevel = "Serializable"
)

type GameScalarFieldEnum string

const (
	GameScalarFieldEnumID          GameScalarFieldEnum = "id"
	GameScalarFieldEnumTitle       GameScalarFieldEnum = "title"
	GameScalarFieldEnumGenre       GameScalarFieldEnum = "genre"
	GameScalarFieldEnumReleaseDate GameScalarFieldEnum = "releaseDate"
	GameScalarFieldEnumDeveloper   GameScalarFieldEnum = "developer"
	GameScalarFieldEnumCreatedAt   GameScalarFieldEnum = "createdAt"
	GameScalarFieldEnumUpdatedAt   GameScalarFieldEnum = "updatedAt"
)

type SortOrder string

const (
	SortOrderAsc  SortOrder = "asc"
	SortOrderDesc SortOrder = "desc"
)

type QueryMode string

const (
	QueryModeDefault     QueryMode = "default"
	QueryModeInsensitive QueryMode = "insensitive"
)

// --- template errors.gotpl ---
var ErrNotFound = types.ErrNotFound
var IsErrNotFound = types.IsErrNotFound

type ErrUniqueConstraint = types.ErrUniqueConstraint[prismaFields]

// IsErrUniqueConstraint returns on a unique constraint error or violation with error info
// Use as follows:
//
//	user, err := db.User.CreateOne(...).Exec(cxt)
//	if err != nil {
//		if info, err := db.IsErrUniqueConstraint(err); err != nil {
//			// Fields exists for Postgres and SQLite
//			log.Printf("unique constraint on the fields: %s", info.Fields)
//
//			// you can also compare it with generated field names:
//			if info.Fields[0] == db.User.Name.Field() {
//				// do something
//			}
//
//			// For MySQL, use the constraint key
//			log.Printf("unique constraint on the key: %s", info.Key)
//		}
//	}
func IsErrUniqueConstraint(err error) (*types.ErrUniqueConstraint[prismaFields], bool) {
	return types.CheckUniqueConstraint[prismaFields](err)
}

// --- template fields.gotpl ---
type prismaFields string

type gamePrismaFields = prismaFields

const gameFieldID gamePrismaFields = "id"

const gameFieldTitle gamePrismaFields = "title"

const gameFieldGenre gamePrismaFields = "genre"

const gameFieldReleaseDate gamePrismaFields = "releaseDate"

const gameFieldDeveloper gamePrismaFields = "developer"

const gameFieldCreatedAt gamePrismaFields = "createdAt"

const gameFieldUpdatedAt gamePrismaFields = "updatedAt"

// --- template mock.gotpl ---
func NewMock() (*PrismaClient, *Mock, func(t *testing.T)) {
	expectations := new([]mock.Expectation)
	pc := newMockClient(expectations)
	m := &Mock{
		Mock: &mock.Mock{
			Expectations: expectations,
		},
	}

	m.Game = gameMock{
		mock: m,
	}

	return pc, m, m.Ensure
}

type Mock struct {
	*mock.Mock

	Game gameMock
}

type gameMock struct {
	mock *Mock
}

type GameMockExpectParam interface {
	ExtractQuery() builder.Query
	gameModel()
}

func (m *gameMock) Expect(query GameMockExpectParam) *gameMockExec {
	return &gameMockExec{
		mock:  m.mock,
		query: query.ExtractQuery(),
	}
}

type gameMockExec struct {
	mock  *Mock
	query builder.Query
}

func (m *gameMockExec) Returns(v GameModel) {
	*m.mock.Expectations = append(*m.mock.Expectations, mock.Expectation{
		Query: m.query,
		Want:  &v,
	})
}

func (m *gameMockExec) ReturnsMany(v []GameModel) {
	*m.mock.Expectations = append(*m.mock.Expectations, mock.Expectation{
		Query: m.query,
		Want:  &v,
	})
}

func (m *gameMockExec) Errors(err error) {
	*m.mock.Expectations = append(*m.mock.Expectations, mock.Expectation{
		Query:   m.query,
		WantErr: err,
	})
}

// --- template models.gotpl ---

// GameModel represents the Game model and is a wrapper for accessing fields and methods
type GameModel struct {
	InnerGame
	RelationsGame
}

// InnerGame holds the actual data
type InnerGame struct {
	ID          int      `json:"id"`
	Title       string   `json:"title"`
	Genre       string   `json:"genre"`
	ReleaseDate DateTime `json:"releaseDate"`
	Developer   string   `json:"developer"`
	CreatedAt   DateTime `json:"createdAt"`
	UpdatedAt   DateTime `json:"updatedAt"`
}

// RawGameModel is a struct for Game when used in raw queries
type RawGameModel struct {
	ID          RawInt      `json:"id"`
	Title       RawString   `json:"title"`
	Genre       RawString   `json:"genre"`
	ReleaseDate RawDateTime `json:"releaseDate"`
	Developer   RawString   `json:"developer"`
	CreatedAt   RawDateTime `json:"createdAt"`
	UpdatedAt   RawDateTime `json:"updatedAt"`
}

// RelationsGame holds the relation data separately
type RelationsGame struct {
}

// --- template query.gotpl ---

// Game acts as a namespaces to access query methods for the Game model
var Game = gameQuery{}

// gameQuery exposes query functions for the game model
type gameQuery struct {

	// ID
	//
	// @required
	ID gameQueryIDInt

	// Title
	//
	// @required
	Title gameQueryTitleString

	// Genre
	//
	// @required
	Genre gameQueryGenreString

	// ReleaseDate
	//
	// @required
	ReleaseDate gameQueryReleaseDateDateTime

	// Developer
	//
	// @required
	Developer gameQueryDeveloperString

	// CreatedAt
	//
	// @required
	CreatedAt gameQueryCreatedAtDateTime

	// UpdatedAt
	//
	// @required
	UpdatedAt gameQueryUpdatedAtDateTime
}

func (gameQuery) Not(params ...GameWhereParam) gameDefaultParam {
	var fields []builder.Field

	for _, q := range params {
		fields = append(fields, q.field())
	}

	return gameDefaultParam{
		data: builder.Field{
			Name:     "NOT",
			List:     true,
			WrapList: true,
			Fields:   fields,
		},
	}
}

func (gameQuery) Or(params ...GameWhereParam) gameDefaultParam {
	var fields []builder.Field

	for _, q := range params {
		fields = append(fields, q.field())
	}

	return gameDefaultParam{
		data: builder.Field{
			Name:     "OR",
			List:     true,
			WrapList: true,
			Fields:   fields,
		},
	}
}

func (gameQuery) And(params ...GameWhereParam) gameDefaultParam {
	var fields []builder.Field

	for _, q := range params {
		fields = append(fields, q.field())
	}

	return gameDefaultParam{
		data: builder.Field{
			Name:     "AND",
			List:     true,
			WrapList: true,
			Fields:   fields,
		},
	}
}

// base struct
type gameQueryIDInt struct{}

// Set the required value of ID
func (r gameQueryIDInt) Set(value int) gameSetParam {

	return gameSetParam{
		data: builder.Field{
			Name:  "id",
			Value: value,
		},
	}

}

// Set the optional value of ID dynamically
func (r gameQueryIDInt) SetIfPresent(value *Int) gameSetParam {
	if value == nil {
		return gameSetParam{}
	}

	return r.Set(*value)
}

// Increment the required value of ID
func (r gameQueryIDInt) Increment(value int) gameSetParam {
	return gameSetParam{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				builder.Field{
					Name:  "increment",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) IncrementIfPresent(value *int) gameSetParam {
	if value == nil {
		return gameSetParam{}
	}
	return r.Increment(*value)
}

// Decrement the required value of ID
func (r gameQueryIDInt) Decrement(value int) gameSetParam {
	return gameSetParam{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				builder.Field{
					Name:  "decrement",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) DecrementIfPresent(value *int) gameSetParam {
	if value == nil {
		return gameSetParam{}
	}
	return r.Decrement(*value)
}

// Multiply the required value of ID
func (r gameQueryIDInt) Multiply(value int) gameSetParam {
	return gameSetParam{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				builder.Field{
					Name:  "multiply",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) MultiplyIfPresent(value *int) gameSetParam {
	if value == nil {
		return gameSetParam{}
	}
	return r.Multiply(*value)
}

// Divide the required value of ID
func (r gameQueryIDInt) Divide(value int) gameSetParam {
	return gameSetParam{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				builder.Field{
					Name:  "divide",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) DivideIfPresent(value *int) gameSetParam {
	if value == nil {
		return gameSetParam{}
	}
	return r.Divide(*value)
}

func (r gameQueryIDInt) Equals(value int) gameWithPrismaIDEqualsUniqueParam {

	return gameWithPrismaIDEqualsUniqueParam{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "equals",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) EqualsIfPresent(value *int) gameWithPrismaIDEqualsUniqueParam {
	if value == nil {
		return gameWithPrismaIDEqualsUniqueParam{}
	}
	return r.Equals(*value)
}

func (r gameQueryIDInt) Order(direction SortOrder) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name:  "id",
			Value: direction,
		},
	}
}

func (r gameQueryIDInt) Cursor(cursor int) gameCursorParam {
	return gameCursorParam{
		data: builder.Field{
			Name:  "id",
			Value: cursor,
		},
	}
}

func (r gameQueryIDInt) In(value []int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "in",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) InIfPresent(value []int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.In(value)
}

func (r gameQueryIDInt) NotIn(value []int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "notIn",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) NotInIfPresent(value []int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.NotIn(value)
}

func (r gameQueryIDInt) Lt(value int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) LtIfPresent(value *int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.Lt(*value)
}

func (r gameQueryIDInt) Lte(value int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) LteIfPresent(value *int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.Lte(*value)
}

func (r gameQueryIDInt) Gt(value int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) GtIfPresent(value *int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.Gt(*value)
}

func (r gameQueryIDInt) Gte(value int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) GteIfPresent(value *int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.Gte(*value)
}

func (r gameQueryIDInt) Not(value int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "not",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryIDInt) NotIfPresent(value *int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.Not(*value)
}

// deprecated: Use Lt instead.

func (r gameQueryIDInt) LT(value int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use LtIfPresent instead.
func (r gameQueryIDInt) LTIfPresent(value *int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.LT(*value)
}

// deprecated: Use Lte instead.

func (r gameQueryIDInt) LTE(value int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use LteIfPresent instead.
func (r gameQueryIDInt) LTEIfPresent(value *int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.LTE(*value)
}

// deprecated: Use Gt instead.

func (r gameQueryIDInt) GT(value int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use GtIfPresent instead.
func (r gameQueryIDInt) GTIfPresent(value *int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.GT(*value)
}

// deprecated: Use Gte instead.

func (r gameQueryIDInt) GTE(value int) gameParamUnique {
	return gameParamUnique{
		data: builder.Field{
			Name: "id",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use GteIfPresent instead.
func (r gameQueryIDInt) GTEIfPresent(value *int) gameParamUnique {
	if value == nil {
		return gameParamUnique{}
	}
	return r.GTE(*value)
}

func (r gameQueryIDInt) Field() gamePrismaFields {
	return gameFieldID
}

// base struct
type gameQueryTitleString struct{}

// Set the required value of Title
func (r gameQueryTitleString) Set(value string) gameWithPrismaTitleSetParam {

	return gameWithPrismaTitleSetParam{
		data: builder.Field{
			Name:  "title",
			Value: value,
		},
	}

}

// Set the optional value of Title dynamically
func (r gameQueryTitleString) SetIfPresent(value *String) gameWithPrismaTitleSetParam {
	if value == nil {
		return gameWithPrismaTitleSetParam{}
	}

	return r.Set(*value)
}

func (r gameQueryTitleString) Equals(value string) gameWithPrismaTitleEqualsParam {

	return gameWithPrismaTitleEqualsParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "equals",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) EqualsIfPresent(value *string) gameWithPrismaTitleEqualsParam {
	if value == nil {
		return gameWithPrismaTitleEqualsParam{}
	}
	return r.Equals(*value)
}

func (r gameQueryTitleString) Order(direction SortOrder) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name:  "title",
			Value: direction,
		},
	}
}

func (r gameQueryTitleString) Cursor(cursor string) gameCursorParam {
	return gameCursorParam{
		data: builder.Field{
			Name:  "title",
			Value: cursor,
		},
	}
}

func (r gameQueryTitleString) In(value []string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "in",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) InIfPresent(value []string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.In(value)
}

func (r gameQueryTitleString) NotIn(value []string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "notIn",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) NotInIfPresent(value []string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.NotIn(value)
}

func (r gameQueryTitleString) Lt(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) LtIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lt(*value)
}

func (r gameQueryTitleString) Lte(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) LteIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lte(*value)
}

func (r gameQueryTitleString) Gt(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) GtIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gt(*value)
}

func (r gameQueryTitleString) Gte(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) GteIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gte(*value)
}

func (r gameQueryTitleString) Contains(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "contains",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) ContainsIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Contains(*value)
}

func (r gameQueryTitleString) StartsWith(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "startsWith",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) StartsWithIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.StartsWith(*value)
}

func (r gameQueryTitleString) EndsWith(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "endsWith",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) EndsWithIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.EndsWith(*value)
}

func (r gameQueryTitleString) Mode(value QueryMode) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "mode",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) ModeIfPresent(value *QueryMode) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Mode(*value)
}

func (r gameQueryTitleString) Not(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "not",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryTitleString) NotIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Not(*value)
}

// deprecated: Use StartsWith instead.

func (r gameQueryTitleString) HasPrefix(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "starts_with",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use StartsWithIfPresent instead.
func (r gameQueryTitleString) HasPrefixIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.HasPrefix(*value)
}

// deprecated: Use EndsWith instead.

func (r gameQueryTitleString) HasSuffix(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "title",
			Fields: []builder.Field{
				{
					Name:  "ends_with",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use EndsWithIfPresent instead.
func (r gameQueryTitleString) HasSuffixIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.HasSuffix(*value)
}

func (r gameQueryTitleString) Field() gamePrismaFields {
	return gameFieldTitle
}

// base struct
type gameQueryGenreString struct{}

// Set the required value of Genre
func (r gameQueryGenreString) Set(value string) gameWithPrismaGenreSetParam {

	return gameWithPrismaGenreSetParam{
		data: builder.Field{
			Name:  "genre",
			Value: value,
		},
	}

}

// Set the optional value of Genre dynamically
func (r gameQueryGenreString) SetIfPresent(value *String) gameWithPrismaGenreSetParam {
	if value == nil {
		return gameWithPrismaGenreSetParam{}
	}

	return r.Set(*value)
}

func (r gameQueryGenreString) Equals(value string) gameWithPrismaGenreEqualsParam {

	return gameWithPrismaGenreEqualsParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "equals",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) EqualsIfPresent(value *string) gameWithPrismaGenreEqualsParam {
	if value == nil {
		return gameWithPrismaGenreEqualsParam{}
	}
	return r.Equals(*value)
}

func (r gameQueryGenreString) Order(direction SortOrder) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name:  "genre",
			Value: direction,
		},
	}
}

func (r gameQueryGenreString) Cursor(cursor string) gameCursorParam {
	return gameCursorParam{
		data: builder.Field{
			Name:  "genre",
			Value: cursor,
		},
	}
}

func (r gameQueryGenreString) In(value []string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "in",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) InIfPresent(value []string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.In(value)
}

func (r gameQueryGenreString) NotIn(value []string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "notIn",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) NotInIfPresent(value []string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.NotIn(value)
}

func (r gameQueryGenreString) Lt(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) LtIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lt(*value)
}

func (r gameQueryGenreString) Lte(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) LteIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lte(*value)
}

func (r gameQueryGenreString) Gt(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) GtIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gt(*value)
}

func (r gameQueryGenreString) Gte(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) GteIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gte(*value)
}

func (r gameQueryGenreString) Contains(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "contains",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) ContainsIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Contains(*value)
}

func (r gameQueryGenreString) StartsWith(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "startsWith",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) StartsWithIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.StartsWith(*value)
}

func (r gameQueryGenreString) EndsWith(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "endsWith",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) EndsWithIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.EndsWith(*value)
}

func (r gameQueryGenreString) Mode(value QueryMode) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "mode",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) ModeIfPresent(value *QueryMode) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Mode(*value)
}

func (r gameQueryGenreString) Not(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "not",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryGenreString) NotIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Not(*value)
}

// deprecated: Use StartsWith instead.

func (r gameQueryGenreString) HasPrefix(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "starts_with",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use StartsWithIfPresent instead.
func (r gameQueryGenreString) HasPrefixIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.HasPrefix(*value)
}

// deprecated: Use EndsWith instead.

func (r gameQueryGenreString) HasSuffix(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "genre",
			Fields: []builder.Field{
				{
					Name:  "ends_with",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use EndsWithIfPresent instead.
func (r gameQueryGenreString) HasSuffixIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.HasSuffix(*value)
}

func (r gameQueryGenreString) Field() gamePrismaFields {
	return gameFieldGenre
}

// base struct
type gameQueryReleaseDateDateTime struct{}

// Set the required value of ReleaseDate
func (r gameQueryReleaseDateDateTime) Set(value DateTime) gameWithPrismaReleaseDateSetParam {

	return gameWithPrismaReleaseDateSetParam{
		data: builder.Field{
			Name:  "releaseDate",
			Value: value,
		},
	}

}

// Set the optional value of ReleaseDate dynamically
func (r gameQueryReleaseDateDateTime) SetIfPresent(value *DateTime) gameWithPrismaReleaseDateSetParam {
	if value == nil {
		return gameWithPrismaReleaseDateSetParam{}
	}

	return r.Set(*value)
}

func (r gameQueryReleaseDateDateTime) Equals(value DateTime) gameWithPrismaReleaseDateEqualsParam {

	return gameWithPrismaReleaseDateEqualsParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "equals",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryReleaseDateDateTime) EqualsIfPresent(value *DateTime) gameWithPrismaReleaseDateEqualsParam {
	if value == nil {
		return gameWithPrismaReleaseDateEqualsParam{}
	}
	return r.Equals(*value)
}

func (r gameQueryReleaseDateDateTime) Order(direction SortOrder) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name:  "releaseDate",
			Value: direction,
		},
	}
}

func (r gameQueryReleaseDateDateTime) Cursor(cursor DateTime) gameCursorParam {
	return gameCursorParam{
		data: builder.Field{
			Name:  "releaseDate",
			Value: cursor,
		},
	}
}

func (r gameQueryReleaseDateDateTime) In(value []DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "in",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryReleaseDateDateTime) InIfPresent(value []DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.In(value)
}

func (r gameQueryReleaseDateDateTime) NotIn(value []DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "notIn",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryReleaseDateDateTime) NotInIfPresent(value []DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.NotIn(value)
}

func (r gameQueryReleaseDateDateTime) Lt(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryReleaseDateDateTime) LtIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lt(*value)
}

func (r gameQueryReleaseDateDateTime) Lte(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryReleaseDateDateTime) LteIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lte(*value)
}

func (r gameQueryReleaseDateDateTime) Gt(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryReleaseDateDateTime) GtIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gt(*value)
}

func (r gameQueryReleaseDateDateTime) Gte(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryReleaseDateDateTime) GteIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gte(*value)
}

func (r gameQueryReleaseDateDateTime) Not(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "not",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryReleaseDateDateTime) NotIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Not(*value)
}

// deprecated: Use Lt instead.

func (r gameQueryReleaseDateDateTime) Before(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use LtIfPresent instead.
func (r gameQueryReleaseDateDateTime) BeforeIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Before(*value)
}

// deprecated: Use Gt instead.

func (r gameQueryReleaseDateDateTime) After(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use GtIfPresent instead.
func (r gameQueryReleaseDateDateTime) AfterIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.After(*value)
}

// deprecated: Use Lte instead.

func (r gameQueryReleaseDateDateTime) BeforeEquals(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use LteIfPresent instead.
func (r gameQueryReleaseDateDateTime) BeforeEqualsIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.BeforeEquals(*value)
}

// deprecated: Use Gte instead.

func (r gameQueryReleaseDateDateTime) AfterEquals(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "releaseDate",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use GteIfPresent instead.
func (r gameQueryReleaseDateDateTime) AfterEqualsIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.AfterEquals(*value)
}

func (r gameQueryReleaseDateDateTime) Field() gamePrismaFields {
	return gameFieldReleaseDate
}

// base struct
type gameQueryDeveloperString struct{}

// Set the required value of Developer
func (r gameQueryDeveloperString) Set(value string) gameWithPrismaDeveloperSetParam {

	return gameWithPrismaDeveloperSetParam{
		data: builder.Field{
			Name:  "developer",
			Value: value,
		},
	}

}

// Set the optional value of Developer dynamically
func (r gameQueryDeveloperString) SetIfPresent(value *String) gameWithPrismaDeveloperSetParam {
	if value == nil {
		return gameWithPrismaDeveloperSetParam{}
	}

	return r.Set(*value)
}

func (r gameQueryDeveloperString) Equals(value string) gameWithPrismaDeveloperEqualsParam {

	return gameWithPrismaDeveloperEqualsParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "equals",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) EqualsIfPresent(value *string) gameWithPrismaDeveloperEqualsParam {
	if value == nil {
		return gameWithPrismaDeveloperEqualsParam{}
	}
	return r.Equals(*value)
}

func (r gameQueryDeveloperString) Order(direction SortOrder) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name:  "developer",
			Value: direction,
		},
	}
}

func (r gameQueryDeveloperString) Cursor(cursor string) gameCursorParam {
	return gameCursorParam{
		data: builder.Field{
			Name:  "developer",
			Value: cursor,
		},
	}
}

func (r gameQueryDeveloperString) In(value []string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "in",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) InIfPresent(value []string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.In(value)
}

func (r gameQueryDeveloperString) NotIn(value []string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "notIn",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) NotInIfPresent(value []string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.NotIn(value)
}

func (r gameQueryDeveloperString) Lt(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) LtIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lt(*value)
}

func (r gameQueryDeveloperString) Lte(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) LteIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lte(*value)
}

func (r gameQueryDeveloperString) Gt(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) GtIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gt(*value)
}

func (r gameQueryDeveloperString) Gte(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) GteIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gte(*value)
}

func (r gameQueryDeveloperString) Contains(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "contains",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) ContainsIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Contains(*value)
}

func (r gameQueryDeveloperString) StartsWith(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "startsWith",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) StartsWithIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.StartsWith(*value)
}

func (r gameQueryDeveloperString) EndsWith(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "endsWith",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) EndsWithIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.EndsWith(*value)
}

func (r gameQueryDeveloperString) Mode(value QueryMode) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "mode",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) ModeIfPresent(value *QueryMode) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Mode(*value)
}

func (r gameQueryDeveloperString) Not(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "not",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryDeveloperString) NotIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Not(*value)
}

// deprecated: Use StartsWith instead.

func (r gameQueryDeveloperString) HasPrefix(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "starts_with",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use StartsWithIfPresent instead.
func (r gameQueryDeveloperString) HasPrefixIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.HasPrefix(*value)
}

// deprecated: Use EndsWith instead.

func (r gameQueryDeveloperString) HasSuffix(value string) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "developer",
			Fields: []builder.Field{
				{
					Name:  "ends_with",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use EndsWithIfPresent instead.
func (r gameQueryDeveloperString) HasSuffixIfPresent(value *string) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.HasSuffix(*value)
}

func (r gameQueryDeveloperString) Field() gamePrismaFields {
	return gameFieldDeveloper
}

// base struct
type gameQueryCreatedAtDateTime struct{}

// Set the required value of CreatedAt
func (r gameQueryCreatedAtDateTime) Set(value DateTime) gameSetParam {

	return gameSetParam{
		data: builder.Field{
			Name:  "createdAt",
			Value: value,
		},
	}

}

// Set the optional value of CreatedAt dynamically
func (r gameQueryCreatedAtDateTime) SetIfPresent(value *DateTime) gameSetParam {
	if value == nil {
		return gameSetParam{}
	}

	return r.Set(*value)
}

func (r gameQueryCreatedAtDateTime) Equals(value DateTime) gameWithPrismaCreatedAtEqualsParam {

	return gameWithPrismaCreatedAtEqualsParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "equals",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryCreatedAtDateTime) EqualsIfPresent(value *DateTime) gameWithPrismaCreatedAtEqualsParam {
	if value == nil {
		return gameWithPrismaCreatedAtEqualsParam{}
	}
	return r.Equals(*value)
}

func (r gameQueryCreatedAtDateTime) Order(direction SortOrder) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name:  "createdAt",
			Value: direction,
		},
	}
}

func (r gameQueryCreatedAtDateTime) Cursor(cursor DateTime) gameCursorParam {
	return gameCursorParam{
		data: builder.Field{
			Name:  "createdAt",
			Value: cursor,
		},
	}
}

func (r gameQueryCreatedAtDateTime) In(value []DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "in",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryCreatedAtDateTime) InIfPresent(value []DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.In(value)
}

func (r gameQueryCreatedAtDateTime) NotIn(value []DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "notIn",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryCreatedAtDateTime) NotInIfPresent(value []DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.NotIn(value)
}

func (r gameQueryCreatedAtDateTime) Lt(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryCreatedAtDateTime) LtIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lt(*value)
}

func (r gameQueryCreatedAtDateTime) Lte(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryCreatedAtDateTime) LteIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lte(*value)
}

func (r gameQueryCreatedAtDateTime) Gt(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryCreatedAtDateTime) GtIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gt(*value)
}

func (r gameQueryCreatedAtDateTime) Gte(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryCreatedAtDateTime) GteIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gte(*value)
}

func (r gameQueryCreatedAtDateTime) Not(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "not",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryCreatedAtDateTime) NotIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Not(*value)
}

// deprecated: Use Lt instead.

func (r gameQueryCreatedAtDateTime) Before(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use LtIfPresent instead.
func (r gameQueryCreatedAtDateTime) BeforeIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Before(*value)
}

// deprecated: Use Gt instead.

func (r gameQueryCreatedAtDateTime) After(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use GtIfPresent instead.
func (r gameQueryCreatedAtDateTime) AfterIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.After(*value)
}

// deprecated: Use Lte instead.

func (r gameQueryCreatedAtDateTime) BeforeEquals(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use LteIfPresent instead.
func (r gameQueryCreatedAtDateTime) BeforeEqualsIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.BeforeEquals(*value)
}

// deprecated: Use Gte instead.

func (r gameQueryCreatedAtDateTime) AfterEquals(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "createdAt",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use GteIfPresent instead.
func (r gameQueryCreatedAtDateTime) AfterEqualsIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.AfterEquals(*value)
}

func (r gameQueryCreatedAtDateTime) Field() gamePrismaFields {
	return gameFieldCreatedAt
}

// base struct
type gameQueryUpdatedAtDateTime struct{}

// Set the required value of UpdatedAt
func (r gameQueryUpdatedAtDateTime) Set(value DateTime) gameSetParam {

	return gameSetParam{
		data: builder.Field{
			Name:  "updatedAt",
			Value: value,
		},
	}

}

// Set the optional value of UpdatedAt dynamically
func (r gameQueryUpdatedAtDateTime) SetIfPresent(value *DateTime) gameSetParam {
	if value == nil {
		return gameSetParam{}
	}

	return r.Set(*value)
}

func (r gameQueryUpdatedAtDateTime) Equals(value DateTime) gameWithPrismaUpdatedAtEqualsParam {

	return gameWithPrismaUpdatedAtEqualsParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "equals",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryUpdatedAtDateTime) EqualsIfPresent(value *DateTime) gameWithPrismaUpdatedAtEqualsParam {
	if value == nil {
		return gameWithPrismaUpdatedAtEqualsParam{}
	}
	return r.Equals(*value)
}

func (r gameQueryUpdatedAtDateTime) Order(direction SortOrder) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name:  "updatedAt",
			Value: direction,
		},
	}
}

func (r gameQueryUpdatedAtDateTime) Cursor(cursor DateTime) gameCursorParam {
	return gameCursorParam{
		data: builder.Field{
			Name:  "updatedAt",
			Value: cursor,
		},
	}
}

func (r gameQueryUpdatedAtDateTime) In(value []DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "in",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryUpdatedAtDateTime) InIfPresent(value []DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.In(value)
}

func (r gameQueryUpdatedAtDateTime) NotIn(value []DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "notIn",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryUpdatedAtDateTime) NotInIfPresent(value []DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.NotIn(value)
}

func (r gameQueryUpdatedAtDateTime) Lt(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryUpdatedAtDateTime) LtIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lt(*value)
}

func (r gameQueryUpdatedAtDateTime) Lte(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryUpdatedAtDateTime) LteIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Lte(*value)
}

func (r gameQueryUpdatedAtDateTime) Gt(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryUpdatedAtDateTime) GtIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gt(*value)
}

func (r gameQueryUpdatedAtDateTime) Gte(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryUpdatedAtDateTime) GteIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Gte(*value)
}

func (r gameQueryUpdatedAtDateTime) Not(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "not",
					Value: value,
				},
			},
		},
	}
}

func (r gameQueryUpdatedAtDateTime) NotIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Not(*value)
}

// deprecated: Use Lt instead.

func (r gameQueryUpdatedAtDateTime) Before(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "lt",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use LtIfPresent instead.
func (r gameQueryUpdatedAtDateTime) BeforeIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.Before(*value)
}

// deprecated: Use Gt instead.

func (r gameQueryUpdatedAtDateTime) After(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "gt",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use GtIfPresent instead.
func (r gameQueryUpdatedAtDateTime) AfterIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.After(*value)
}

// deprecated: Use Lte instead.

func (r gameQueryUpdatedAtDateTime) BeforeEquals(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "lte",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use LteIfPresent instead.
func (r gameQueryUpdatedAtDateTime) BeforeEqualsIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.BeforeEquals(*value)
}

// deprecated: Use Gte instead.

func (r gameQueryUpdatedAtDateTime) AfterEquals(value DateTime) gameDefaultParam {
	return gameDefaultParam{
		data: builder.Field{
			Name: "updatedAt",
			Fields: []builder.Field{
				{
					Name:  "gte",
					Value: value,
				},
			},
		},
	}
}

// deprecated: Use GteIfPresent instead.
func (r gameQueryUpdatedAtDateTime) AfterEqualsIfPresent(value *DateTime) gameDefaultParam {
	if value == nil {
		return gameDefaultParam{}
	}
	return r.AfterEquals(*value)
}

func (r gameQueryUpdatedAtDateTime) Field() gamePrismaFields {
	return gameFieldUpdatedAt
}

// --- template actions.gotpl ---
var countOutput = []builder.Output{
	{Name: "count"},
}

type gameActions struct {
	// client holds the prisma client
	client *PrismaClient
}

var gameOutput = []builder.Output{
	{Name: "id"},
	{Name: "title"},
	{Name: "genre"},
	{Name: "releaseDate"},
	{Name: "developer"},
	{Name: "createdAt"},
	{Name: "updatedAt"},
}

type GameRelationWith interface {
	getQuery() builder.Query
	with()
	gameRelation()
}

type GameWhereParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
}

type gameDefaultParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameDefaultParam) field() builder.Field {
	return p.data
}

func (p gameDefaultParam) getQuery() builder.Query {
	return p.query
}

func (p gameDefaultParam) gameModel() {}

type GameOrderByParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
}

type gameOrderByParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameOrderByParam) field() builder.Field {
	return p.data
}

func (p gameOrderByParam) getQuery() builder.Query {
	return p.query
}

func (p gameOrderByParam) gameModel() {}

type GameCursorParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	isCursor()
}

type gameCursorParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameCursorParam) field() builder.Field {
	return p.data
}

func (p gameCursorParam) isCursor() {}

func (p gameCursorParam) getQuery() builder.Query {
	return p.query
}

func (p gameCursorParam) gameModel() {}

type GameParamUnique interface {
	field() builder.Field
	getQuery() builder.Query
	unique()
	gameModel()
}

type gameParamUnique struct {
	data  builder.Field
	query builder.Query
}

func (p gameParamUnique) gameModel() {}

func (gameParamUnique) unique() {}

func (p gameParamUnique) field() builder.Field {
	return p.data
}

func (p gameParamUnique) getQuery() builder.Query {
	return p.query
}

type GameEqualsWhereParam interface {
	field() builder.Field
	getQuery() builder.Query
	equals()
	gameModel()
}

type gameEqualsParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameEqualsParam) gameModel() {}

func (gameEqualsParam) equals() {}

func (p gameEqualsParam) field() builder.Field {
	return p.data
}

func (p gameEqualsParam) getQuery() builder.Query {
	return p.query
}

type GameEqualsUniqueWhereParam interface {
	field() builder.Field
	getQuery() builder.Query
	equals()
	unique()
	gameModel()
}

type gameEqualsUniqueParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameEqualsUniqueParam) gameModel() {}

func (gameEqualsUniqueParam) unique() {}
func (gameEqualsUniqueParam) equals() {}

func (p gameEqualsUniqueParam) field() builder.Field {
	return p.data
}

func (p gameEqualsUniqueParam) getQuery() builder.Query {
	return p.query
}

type GameSetParam interface {
	field() builder.Field
	settable()
	gameModel()
}

type gameSetParam struct {
	data builder.Field
}

func (gameSetParam) settable() {}

func (p gameSetParam) field() builder.Field {
	return p.data
}

func (p gameSetParam) gameModel() {}

type GameWithPrismaIDEqualsSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	equals()
	gameModel()
	idField()
}

type GameWithPrismaIDSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	idField()
}

type gameWithPrismaIDSetParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaIDSetParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaIDSetParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaIDSetParam) gameModel() {}

func (p gameWithPrismaIDSetParam) idField() {}

type GameWithPrismaIDWhereParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	idField()
}

type gameWithPrismaIDEqualsParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaIDEqualsParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaIDEqualsParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaIDEqualsParam) gameModel() {}

func (p gameWithPrismaIDEqualsParam) idField() {}

func (gameWithPrismaIDSetParam) settable()  {}
func (gameWithPrismaIDEqualsParam) equals() {}

type gameWithPrismaIDEqualsUniqueParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaIDEqualsUniqueParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaIDEqualsUniqueParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaIDEqualsUniqueParam) gameModel() {}
func (p gameWithPrismaIDEqualsUniqueParam) idField()   {}

func (gameWithPrismaIDEqualsUniqueParam) unique() {}
func (gameWithPrismaIDEqualsUniqueParam) equals() {}

type GameWithPrismaTitleEqualsSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	equals()
	gameModel()
	titleField()
}

type GameWithPrismaTitleSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	titleField()
}

type gameWithPrismaTitleSetParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaTitleSetParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaTitleSetParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaTitleSetParam) gameModel() {}

func (p gameWithPrismaTitleSetParam) titleField() {}

type GameWithPrismaTitleWhereParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	titleField()
}

type gameWithPrismaTitleEqualsParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaTitleEqualsParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaTitleEqualsParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaTitleEqualsParam) gameModel() {}

func (p gameWithPrismaTitleEqualsParam) titleField() {}

func (gameWithPrismaTitleSetParam) settable()  {}
func (gameWithPrismaTitleEqualsParam) equals() {}

type gameWithPrismaTitleEqualsUniqueParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaTitleEqualsUniqueParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaTitleEqualsUniqueParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaTitleEqualsUniqueParam) gameModel()  {}
func (p gameWithPrismaTitleEqualsUniqueParam) titleField() {}

func (gameWithPrismaTitleEqualsUniqueParam) unique() {}
func (gameWithPrismaTitleEqualsUniqueParam) equals() {}

type GameWithPrismaGenreEqualsSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	equals()
	gameModel()
	genreField()
}

type GameWithPrismaGenreSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	genreField()
}

type gameWithPrismaGenreSetParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaGenreSetParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaGenreSetParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaGenreSetParam) gameModel() {}

func (p gameWithPrismaGenreSetParam) genreField() {}

type GameWithPrismaGenreWhereParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	genreField()
}

type gameWithPrismaGenreEqualsParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaGenreEqualsParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaGenreEqualsParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaGenreEqualsParam) gameModel() {}

func (p gameWithPrismaGenreEqualsParam) genreField() {}

func (gameWithPrismaGenreSetParam) settable()  {}
func (gameWithPrismaGenreEqualsParam) equals() {}

type gameWithPrismaGenreEqualsUniqueParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaGenreEqualsUniqueParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaGenreEqualsUniqueParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaGenreEqualsUniqueParam) gameModel()  {}
func (p gameWithPrismaGenreEqualsUniqueParam) genreField() {}

func (gameWithPrismaGenreEqualsUniqueParam) unique() {}
func (gameWithPrismaGenreEqualsUniqueParam) equals() {}

type GameWithPrismaReleaseDateEqualsSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	equals()
	gameModel()
	releaseDateField()
}

type GameWithPrismaReleaseDateSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	releaseDateField()
}

type gameWithPrismaReleaseDateSetParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaReleaseDateSetParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaReleaseDateSetParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaReleaseDateSetParam) gameModel() {}

func (p gameWithPrismaReleaseDateSetParam) releaseDateField() {}

type GameWithPrismaReleaseDateWhereParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	releaseDateField()
}

type gameWithPrismaReleaseDateEqualsParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaReleaseDateEqualsParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaReleaseDateEqualsParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaReleaseDateEqualsParam) gameModel() {}

func (p gameWithPrismaReleaseDateEqualsParam) releaseDateField() {}

func (gameWithPrismaReleaseDateSetParam) settable()  {}
func (gameWithPrismaReleaseDateEqualsParam) equals() {}

type gameWithPrismaReleaseDateEqualsUniqueParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaReleaseDateEqualsUniqueParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaReleaseDateEqualsUniqueParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaReleaseDateEqualsUniqueParam) gameModel()        {}
func (p gameWithPrismaReleaseDateEqualsUniqueParam) releaseDateField() {}

func (gameWithPrismaReleaseDateEqualsUniqueParam) unique() {}
func (gameWithPrismaReleaseDateEqualsUniqueParam) equals() {}

type GameWithPrismaDeveloperEqualsSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	equals()
	gameModel()
	developerField()
}

type GameWithPrismaDeveloperSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	developerField()
}

type gameWithPrismaDeveloperSetParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaDeveloperSetParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaDeveloperSetParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaDeveloperSetParam) gameModel() {}

func (p gameWithPrismaDeveloperSetParam) developerField() {}

type GameWithPrismaDeveloperWhereParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	developerField()
}

type gameWithPrismaDeveloperEqualsParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaDeveloperEqualsParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaDeveloperEqualsParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaDeveloperEqualsParam) gameModel() {}

func (p gameWithPrismaDeveloperEqualsParam) developerField() {}

func (gameWithPrismaDeveloperSetParam) settable()  {}
func (gameWithPrismaDeveloperEqualsParam) equals() {}

type gameWithPrismaDeveloperEqualsUniqueParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaDeveloperEqualsUniqueParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaDeveloperEqualsUniqueParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaDeveloperEqualsUniqueParam) gameModel()      {}
func (p gameWithPrismaDeveloperEqualsUniqueParam) developerField() {}

func (gameWithPrismaDeveloperEqualsUniqueParam) unique() {}
func (gameWithPrismaDeveloperEqualsUniqueParam) equals() {}

type GameWithPrismaCreatedAtEqualsSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	equals()
	gameModel()
	createdAtField()
}

type GameWithPrismaCreatedAtSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	createdAtField()
}

type gameWithPrismaCreatedAtSetParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaCreatedAtSetParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaCreatedAtSetParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaCreatedAtSetParam) gameModel() {}

func (p gameWithPrismaCreatedAtSetParam) createdAtField() {}

type GameWithPrismaCreatedAtWhereParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	createdAtField()
}

type gameWithPrismaCreatedAtEqualsParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaCreatedAtEqualsParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaCreatedAtEqualsParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaCreatedAtEqualsParam) gameModel() {}

func (p gameWithPrismaCreatedAtEqualsParam) createdAtField() {}

func (gameWithPrismaCreatedAtSetParam) settable()  {}
func (gameWithPrismaCreatedAtEqualsParam) equals() {}

type gameWithPrismaCreatedAtEqualsUniqueParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaCreatedAtEqualsUniqueParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaCreatedAtEqualsUniqueParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaCreatedAtEqualsUniqueParam) gameModel()      {}
func (p gameWithPrismaCreatedAtEqualsUniqueParam) createdAtField() {}

func (gameWithPrismaCreatedAtEqualsUniqueParam) unique() {}
func (gameWithPrismaCreatedAtEqualsUniqueParam) equals() {}

type GameWithPrismaUpdatedAtEqualsSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	equals()
	gameModel()
	updatedAtField()
}

type GameWithPrismaUpdatedAtSetParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	updatedAtField()
}

type gameWithPrismaUpdatedAtSetParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaUpdatedAtSetParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaUpdatedAtSetParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaUpdatedAtSetParam) gameModel() {}

func (p gameWithPrismaUpdatedAtSetParam) updatedAtField() {}

type GameWithPrismaUpdatedAtWhereParam interface {
	field() builder.Field
	getQuery() builder.Query
	gameModel()
	updatedAtField()
}

type gameWithPrismaUpdatedAtEqualsParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaUpdatedAtEqualsParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaUpdatedAtEqualsParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaUpdatedAtEqualsParam) gameModel() {}

func (p gameWithPrismaUpdatedAtEqualsParam) updatedAtField() {}

func (gameWithPrismaUpdatedAtSetParam) settable()  {}
func (gameWithPrismaUpdatedAtEqualsParam) equals() {}

type gameWithPrismaUpdatedAtEqualsUniqueParam struct {
	data  builder.Field
	query builder.Query
}

func (p gameWithPrismaUpdatedAtEqualsUniqueParam) field() builder.Field {
	return p.data
}

func (p gameWithPrismaUpdatedAtEqualsUniqueParam) getQuery() builder.Query {
	return p.query
}

func (p gameWithPrismaUpdatedAtEqualsUniqueParam) gameModel()      {}
func (p gameWithPrismaUpdatedAtEqualsUniqueParam) updatedAtField() {}

func (gameWithPrismaUpdatedAtEqualsUniqueParam) unique() {}
func (gameWithPrismaUpdatedAtEqualsUniqueParam) equals() {}

// --- template create.gotpl ---

// Creates a single game.
func (r gameActions) CreateOne(
	_title GameWithPrismaTitleSetParam,
	_genre GameWithPrismaGenreSetParam,
	_releaseDate GameWithPrismaReleaseDateSetParam,
	_developer GameWithPrismaDeveloperSetParam,

	optional ...GameSetParam,
) gameCreateOne {
	var v gameCreateOne
	v.query = builder.NewQuery()
	v.query.Engine = r.client

	v.query.Operation = "mutation"
	v.query.Method = "createOne"
	v.query.Model = "Game"
	v.query.Outputs = gameOutput

	var fields []builder.Field

	fields = append(fields, _title.field())
	fields = append(fields, _genre.field())
	fields = append(fields, _releaseDate.field())
	fields = append(fields, _developer.field())

	for _, q := range optional {
		fields = append(fields, q.field())
	}

	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:   "data",
		Fields: fields,
	})
	return v
}

func (r gameCreateOne) With(params ...GameRelationWith) gameCreateOne {
	for _, q := range params {
		query := q.getQuery()
		r.query.Outputs = append(r.query.Outputs, builder.Output{
			Name:    query.Method,
			Inputs:  query.Inputs,
			Outputs: query.Outputs,
		})
	}

	return r
}

type gameCreateOne struct {
	query builder.Query
}

func (p gameCreateOne) ExtractQuery() builder.Query {
	return p.query
}

func (p gameCreateOne) gameModel() {}

func (r gameCreateOne) Exec(ctx context.Context) (*GameModel, error) {
	var v GameModel
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

func (r gameCreateOne) Tx() GameUniqueTxResult {
	v := newGameUniqueTxResult()
	v.query = r.query
	v.query.TxResult = make(chan []byte, 1)
	return v
}

// --- template find.gotpl ---

type gameFindUnique struct {
	query builder.Query
}

func (r gameFindUnique) getQuery() builder.Query {
	return r.query
}

func (r gameFindUnique) ExtractQuery() builder.Query {
	return r.query
}

func (r gameFindUnique) with()         {}
func (r gameFindUnique) gameModel()    {}
func (r gameFindUnique) gameRelation() {}

func (r gameActions) FindUnique(
	params GameEqualsUniqueWhereParam,
) gameFindUnique {
	var v gameFindUnique
	v.query = builder.NewQuery()
	v.query.Engine = r.client

	v.query.Operation = "query"

	v.query.Method = "findUnique"

	v.query.Model = "Game"
	v.query.Outputs = gameOutput

	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:   "where",
		Fields: builder.TransformEquals([]builder.Field{params.field()}),
	})

	return v
}

func (r gameFindUnique) With(params ...GameRelationWith) gameFindUnique {
	for _, q := range params {
		query := q.getQuery()
		r.query.Outputs = append(r.query.Outputs, builder.Output{
			Name:    query.Method,
			Inputs:  query.Inputs,
			Outputs: query.Outputs,
		})
	}

	return r
}

func (r gameFindUnique) Select(params ...gamePrismaFields) gameFindUnique {
	var outputs []builder.Output

	for _, param := range params {
		outputs = append(outputs, builder.Output{
			Name: string(param),
		})
	}

	r.query.Outputs = outputs

	return r
}

func (r gameFindUnique) Omit(params ...gamePrismaFields) gameFindUnique {
	var outputs []builder.Output

	var raw []string
	for _, param := range params {
		raw = append(raw, string(param))
	}

	for _, output := range gameOutput {
		if !slices.Contains(raw, output.Name) {
			outputs = append(outputs, output)
		}
	}

	r.query.Outputs = outputs

	return r
}

func (r gameFindUnique) Exec(ctx context.Context) (
	*GameModel,
	error,
) {
	var v *GameModel
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}

	if v == nil {
		return nil, ErrNotFound
	}

	return v, nil
}

func (r gameFindUnique) ExecInner(ctx context.Context) (
	*InnerGame,
	error,
) {
	var v *InnerGame
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}

	if v == nil {
		return nil, ErrNotFound
	}

	return v, nil
}

func (r gameFindUnique) Update(params ...GameSetParam) gameUpdateUnique {
	r.query.Operation = "mutation"
	r.query.Method = "updateOne"
	r.query.Model = "Game"

	var v gameUpdateUnique
	v.query = r.query
	var fields []builder.Field
	for _, q := range params {

		field := q.field()

		_, isJson := field.Value.(types.JSON)
		if field.Value != nil && !isJson {
			v := field.Value
			field.Fields = []builder.Field{
				{
					Name:  "set",
					Value: v,
				},
			}

			field.Value = nil
		}

		fields = append(fields, field)
	}
	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:   "data",
		Fields: fields,
	})
	return v
}

type gameUpdateUnique struct {
	query builder.Query
}

func (r gameUpdateUnique) ExtractQuery() builder.Query {
	return r.query
}

func (r gameUpdateUnique) gameModel() {}

func (r gameUpdateUnique) Exec(ctx context.Context) (*GameModel, error) {
	var v GameModel
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

func (r gameUpdateUnique) Tx() GameUniqueTxResult {
	v := newGameUniqueTxResult()
	v.query = r.query
	v.query.TxResult = make(chan []byte, 1)
	return v
}

func (r gameFindUnique) Delete() gameDeleteUnique {
	var v gameDeleteUnique
	v.query = r.query
	v.query.Operation = "mutation"
	v.query.Method = "deleteOne"
	v.query.Model = "Game"

	return v
}

type gameDeleteUnique struct {
	query builder.Query
}

func (r gameDeleteUnique) ExtractQuery() builder.Query {
	return r.query
}

func (p gameDeleteUnique) gameModel() {}

func (r gameDeleteUnique) Exec(ctx context.Context) (*GameModel, error) {
	var v GameModel
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

func (r gameDeleteUnique) Tx() GameUniqueTxResult {
	v := newGameUniqueTxResult()
	v.query = r.query
	v.query.TxResult = make(chan []byte, 1)
	return v
}

type gameFindFirst struct {
	query builder.Query
}

func (r gameFindFirst) getQuery() builder.Query {
	return r.query
}

func (r gameFindFirst) ExtractQuery() builder.Query {
	return r.query
}

func (r gameFindFirst) with()         {}
func (r gameFindFirst) gameModel()    {}
func (r gameFindFirst) gameRelation() {}

func (r gameActions) FindFirst(
	params ...GameWhereParam,
) gameFindFirst {
	var v gameFindFirst
	v.query = builder.NewQuery()
	v.query.Engine = r.client

	v.query.Operation = "query"

	v.query.Method = "findFirst"

	v.query.Model = "Game"
	v.query.Outputs = gameOutput

	var where []builder.Field
	for _, q := range params {
		if query := q.getQuery(); query.Operation != "" {
			v.query.Outputs = append(v.query.Outputs, builder.Output{
				Name:    query.Method,
				Inputs:  query.Inputs,
				Outputs: query.Outputs,
			})
		} else {
			where = append(where, q.field())
		}
	}

	if len(where) > 0 {
		v.query.Inputs = append(v.query.Inputs, builder.Input{
			Name:   "where",
			Fields: where,
		})
	}

	return v
}

func (r gameFindFirst) With(params ...GameRelationWith) gameFindFirst {
	for _, q := range params {
		query := q.getQuery()
		r.query.Outputs = append(r.query.Outputs, builder.Output{
			Name:    query.Method,
			Inputs:  query.Inputs,
			Outputs: query.Outputs,
		})
	}

	return r
}

func (r gameFindFirst) Select(params ...gamePrismaFields) gameFindFirst {
	var outputs []builder.Output

	for _, param := range params {
		outputs = append(outputs, builder.Output{
			Name: string(param),
		})
	}

	r.query.Outputs = outputs

	return r
}

func (r gameFindFirst) Omit(params ...gamePrismaFields) gameFindFirst {
	var outputs []builder.Output

	var raw []string
	for _, param := range params {
		raw = append(raw, string(param))
	}

	for _, output := range gameOutput {
		if !slices.Contains(raw, output.Name) {
			outputs = append(outputs, output)
		}
	}

	r.query.Outputs = outputs

	return r
}

func (r gameFindFirst) OrderBy(params ...GameOrderByParam) gameFindFirst {
	var fields []builder.Field

	for _, param := range params {
		fields = append(fields, builder.Field{
			Name:   param.field().Name,
			Value:  param.field().Value,
			Fields: param.field().Fields,
		})
	}

	r.query.Inputs = append(r.query.Inputs, builder.Input{
		Name:     "orderBy",
		Fields:   fields,
		WrapList: true,
	})

	return r
}

func (r gameFindFirst) Skip(count int) gameFindFirst {
	r.query.Inputs = append(r.query.Inputs, builder.Input{
		Name:  "skip",
		Value: count,
	})
	return r
}

func (r gameFindFirst) Take(count int) gameFindFirst {
	r.query.Inputs = append(r.query.Inputs, builder.Input{
		Name:  "take",
		Value: count,
	})
	return r
}

func (r gameFindFirst) Cursor(cursor GameCursorParam) gameFindFirst {
	r.query.Inputs = append(r.query.Inputs, builder.Input{
		Name:   "cursor",
		Fields: []builder.Field{cursor.field()},
	})
	return r
}

func (r gameFindFirst) Exec(ctx context.Context) (
	*GameModel,
	error,
) {
	var v *GameModel
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}

	if v == nil {
		return nil, ErrNotFound
	}

	return v, nil
}

func (r gameFindFirst) ExecInner(ctx context.Context) (
	*InnerGame,
	error,
) {
	var v *InnerGame
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}

	if v == nil {
		return nil, ErrNotFound
	}

	return v, nil
}

type gameFindMany struct {
	query builder.Query
}

func (r gameFindMany) getQuery() builder.Query {
	return r.query
}

func (r gameFindMany) ExtractQuery() builder.Query {
	return r.query
}

func (r gameFindMany) with()         {}
func (r gameFindMany) gameModel()    {}
func (r gameFindMany) gameRelation() {}

func (r gameActions) FindMany(
	params ...GameWhereParam,
) gameFindMany {
	var v gameFindMany
	v.query = builder.NewQuery()
	v.query.Engine = r.client

	v.query.Operation = "query"

	v.query.Method = "findMany"

	v.query.Model = "Game"
	v.query.Outputs = gameOutput

	var where []builder.Field
	for _, q := range params {
		if query := q.getQuery(); query.Operation != "" {
			v.query.Outputs = append(v.query.Outputs, builder.Output{
				Name:    query.Method,
				Inputs:  query.Inputs,
				Outputs: query.Outputs,
			})
		} else {
			where = append(where, q.field())
		}
	}

	if len(where) > 0 {
		v.query.Inputs = append(v.query.Inputs, builder.Input{
			Name:   "where",
			Fields: where,
		})
	}

	return v
}

func (r gameFindMany) With(params ...GameRelationWith) gameFindMany {
	for _, q := range params {
		query := q.getQuery()
		r.query.Outputs = append(r.query.Outputs, builder.Output{
			Name:    query.Method,
			Inputs:  query.Inputs,
			Outputs: query.Outputs,
		})
	}

	return r
}

func (r gameFindMany) Select(params ...gamePrismaFields) gameFindMany {
	var outputs []builder.Output

	for _, param := range params {
		outputs = append(outputs, builder.Output{
			Name: string(param),
		})
	}

	r.query.Outputs = outputs

	return r
}

func (r gameFindMany) Omit(params ...gamePrismaFields) gameFindMany {
	var outputs []builder.Output

	var raw []string
	for _, param := range params {
		raw = append(raw, string(param))
	}

	for _, output := range gameOutput {
		if !slices.Contains(raw, output.Name) {
			outputs = append(outputs, output)
		}
	}

	r.query.Outputs = outputs

	return r
}

func (r gameFindMany) OrderBy(params ...GameOrderByParam) gameFindMany {
	var fields []builder.Field

	for _, param := range params {
		fields = append(fields, builder.Field{
			Name:   param.field().Name,
			Value:  param.field().Value,
			Fields: param.field().Fields,
		})
	}

	r.query.Inputs = append(r.query.Inputs, builder.Input{
		Name:     "orderBy",
		Fields:   fields,
		WrapList: true,
	})

	return r
}

func (r gameFindMany) Skip(count int) gameFindMany {
	r.query.Inputs = append(r.query.Inputs, builder.Input{
		Name:  "skip",
		Value: count,
	})
	return r
}

func (r gameFindMany) Take(count int) gameFindMany {
	r.query.Inputs = append(r.query.Inputs, builder.Input{
		Name:  "take",
		Value: count,
	})
	return r
}

func (r gameFindMany) Cursor(cursor GameCursorParam) gameFindMany {
	r.query.Inputs = append(r.query.Inputs, builder.Input{
		Name:   "cursor",
		Fields: []builder.Field{cursor.field()},
	})
	return r
}

func (r gameFindMany) Exec(ctx context.Context) (
	[]GameModel,
	error,
) {
	var v []GameModel
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}

	return v, nil
}

func (r gameFindMany) ExecInner(ctx context.Context) (
	[]InnerGame,
	error,
) {
	var v []InnerGame
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}

	return v, nil
}

func (r gameFindMany) Update(params ...GameSetParam) gameUpdateMany {
	r.query.Operation = "mutation"
	r.query.Method = "updateMany"
	r.query.Model = "Game"

	r.query.Outputs = countOutput

	var v gameUpdateMany
	v.query = r.query
	var fields []builder.Field
	for _, q := range params {

		field := q.field()

		_, isJson := field.Value.(types.JSON)
		if field.Value != nil && !isJson {
			v := field.Value
			field.Fields = []builder.Field{
				{
					Name:  "set",
					Value: v,
				},
			}

			field.Value = nil
		}

		fields = append(fields, field)
	}
	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:   "data",
		Fields: fields,
	})
	return v
}

type gameUpdateMany struct {
	query builder.Query
}

func (r gameUpdateMany) ExtractQuery() builder.Query {
	return r.query
}

func (r gameUpdateMany) gameModel() {}

func (r gameUpdateMany) Exec(ctx context.Context) (*BatchResult, error) {
	var v BatchResult
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

func (r gameUpdateMany) Tx() GameManyTxResult {
	v := newGameManyTxResult()
	v.query = r.query
	v.query.TxResult = make(chan []byte, 1)
	return v
}

func (r gameFindMany) Delete() gameDeleteMany {
	var v gameDeleteMany
	v.query = r.query
	v.query.Operation = "mutation"
	v.query.Method = "deleteMany"
	v.query.Model = "Game"

	v.query.Outputs = countOutput

	return v
}

type gameDeleteMany struct {
	query builder.Query
}

func (r gameDeleteMany) ExtractQuery() builder.Query {
	return r.query
}

func (p gameDeleteMany) gameModel() {}

func (r gameDeleteMany) Exec(ctx context.Context) (*BatchResult, error) {
	var v BatchResult
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

func (r gameDeleteMany) Tx() GameManyTxResult {
	v := newGameManyTxResult()
	v.query = r.query
	v.query.TxResult = make(chan []byte, 1)
	return v
}

// --- template transaction.gotpl ---

func newGameUniqueTxResult() GameUniqueTxResult {
	return GameUniqueTxResult{
		result: &transaction.Result{},
	}
}

type GameUniqueTxResult struct {
	query  builder.Query
	result *transaction.Result
}

func (p GameUniqueTxResult) ExtractQuery() builder.Query {
	return p.query
}

func (p GameUniqueTxResult) IsTx() {}

func (r GameUniqueTxResult) Result() (v *GameModel) {
	if err := r.result.Get(r.query.TxResult, &v); err != nil {
		panic(err)
	}
	return v
}

func newGameManyTxResult() GameManyTxResult {
	return GameManyTxResult{
		result: &transaction.Result{},
	}
}

type GameManyTxResult struct {
	query  builder.Query
	result *transaction.Result
}

func (p GameManyTxResult) ExtractQuery() builder.Query {
	return p.query
}

func (p GameManyTxResult) IsTx() {}

func (r GameManyTxResult) Result() (v *BatchResult) {
	if err := r.result.Get(r.query.TxResult, &v); err != nil {
		panic(err)
	}
	return v
}

// --- template upsert.gotpl ---

type gameUpsertOne struct {
	query builder.Query
}

func (r gameUpsertOne) getQuery() builder.Query {
	return r.query
}

func (r gameUpsertOne) ExtractQuery() builder.Query {
	return r.query
}

func (r gameUpsertOne) with()         {}
func (r gameUpsertOne) gameModel()    {}
func (r gameUpsertOne) gameRelation() {}

func (r gameActions) UpsertOne(
	params GameEqualsUniqueWhereParam,
) gameUpsertOne {
	var v gameUpsertOne
	v.query = builder.NewQuery()
	v.query.Engine = r.client

	v.query.Operation = "mutation"
	v.query.Method = "upsertOne"
	v.query.Model = "Game"
	v.query.Outputs = gameOutput

	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:   "where",
		Fields: builder.TransformEquals([]builder.Field{params.field()}),
	})

	return v
}

func (r gameUpsertOne) Create(

	_title GameWithPrismaTitleSetParam,
	_genre GameWithPrismaGenreSetParam,
	_releaseDate GameWithPrismaReleaseDateSetParam,
	_developer GameWithPrismaDeveloperSetParam,

	optional ...GameSetParam,
) gameUpsertOne {
	var v gameUpsertOne
	v.query = r.query

	var fields []builder.Field
	fields = append(fields, _title.field())
	fields = append(fields, _genre.field())
	fields = append(fields, _releaseDate.field())
	fields = append(fields, _developer.field())

	for _, q := range optional {
		fields = append(fields, q.field())
	}

	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:   "create",
		Fields: fields,
	})

	return v
}

func (r gameUpsertOne) Update(
	params ...GameSetParam,
) gameUpsertOne {
	var v gameUpsertOne
	v.query = r.query

	var fields []builder.Field
	for _, q := range params {

		field := q.field()

		_, isJson := field.Value.(types.JSON)
		if field.Value != nil && !isJson {
			v := field.Value
			field.Fields = []builder.Field{
				{
					Name:  "set",
					Value: v,
				},
			}

			field.Value = nil
		}

		fields = append(fields, field)
	}

	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:   "update",
		Fields: fields,
	})

	return v
}

func (r gameUpsertOne) CreateOrUpdate(

	_title GameWithPrismaTitleSetParam,
	_genre GameWithPrismaGenreSetParam,
	_releaseDate GameWithPrismaReleaseDateSetParam,
	_developer GameWithPrismaDeveloperSetParam,

	optional ...GameSetParam,
) gameUpsertOne {
	var v gameUpsertOne
	v.query = r.query

	var fields []builder.Field
	fields = append(fields, _title.field())
	fields = append(fields, _genre.field())
	fields = append(fields, _releaseDate.field())
	fields = append(fields, _developer.field())

	for _, q := range optional {
		fields = append(fields, q.field())
	}

	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:   "create",
		Fields: fields,
	})

	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:   "update",
		Fields: fields,
	})

	return v
}

func (r gameUpsertOne) Exec(ctx context.Context) (*GameModel, error) {
	var v GameModel
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

func (r gameUpsertOne) Tx() GameUniqueTxResult {
	v := newGameUniqueTxResult()
	v.query = r.query
	v.query.TxResult = make(chan []byte, 1)
	return v
}

// --- template raw.gotpl ---

type gameAggregateRaw struct {
	query builder.Query
}

func (r gameAggregateRaw) getQuery() builder.Query {
	return r.query
}

func (r gameAggregateRaw) ExtractQuery() builder.Query {
	return r.query
}

func (r gameAggregateRaw) with()         {}
func (r gameAggregateRaw) gameModel()    {}
func (r gameAggregateRaw) gameRelation() {}

func (r gameActions) FindRaw(filter interface{}, options ...interface{}) gameAggregateRaw {
	var v gameAggregateRaw
	v.query = builder.NewQuery()
	v.query.Engine = r.client
	v.query.Method = "findRaw"
	v.query.Operation = "query"
	v.query.Model = "Game"

	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:  "filter",
		Value: fmt.Sprintf("%v", filter),
	})

	if len(options) > 0 {
		v.query.Inputs = append(v.query.Inputs, builder.Input{
			Name:  "options",
			Value: fmt.Sprintf("%v", options[0]),
		})
	}
	return v
}

func (r gameActions) AggregateRaw(pipeline []interface{}, options ...interface{}) gameAggregateRaw {
	var v gameAggregateRaw
	v.query = builder.NewQuery()
	v.query.Engine = r.client
	v.query.Method = "aggregateRaw"
	v.query.Operation = "query"
	v.query.Model = "Game"

	parsedPip := []interface{}{}
	for _, p := range pipeline {
		parsedPip = append(parsedPip, fmt.Sprintf("%v", p))
	}

	v.query.Inputs = append(v.query.Inputs, builder.Input{
		Name:  "pipeline",
		Value: parsedPip,
	})

	if len(options) > 0 {
		v.query.Inputs = append(v.query.Inputs, builder.Input{
			Name:  "options",
			Value: fmt.Sprintf("%v", options[0]),
		})
	}
	return v
}

func (r gameAggregateRaw) Exec(ctx context.Context) ([]GameModel, error) {
	var v []GameModel
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

func (r gameAggregateRaw) ExecInner(ctx context.Context) ([]InnerGame, error) {
	var v []InnerGame
	if err := r.query.Exec(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}
