-- AlterTable
ALTER TABLE "User" ADD COLUMN     "Badges" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "CurrentLevel" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "CurrentStreak" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "Links" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "MaxStreak" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "PhoneNumber" TEXT;
